#!/bin/sh

# execute this script as root to install the build dependencies

if [ $(id -u) != 0 ]; then
	echo "This script must be executed as root"
	exit 1
fi

# find the appropriate package management tool and install some packages
#
if [ $(which apt) ]; then # install deb dependencies for Debian (as well as Ubuntu) based systems
	apt install g++ make cmake fakeroot rpm qttools5-dev libfftw3-dev binutils-dev \
	  libusb-1.0-0-dev libqt5opengl5-dev mesa-common-dev libgl1-mesa-dev libgles2-mesa-dev
elif [ $(which dnf) ]; then # install rpm dependencies for Fedora based systems
	dnf install make cmake fakeroot gcc-c++ qt5-qtbase-gui qt5-qttools-devel qt5-qttranslations \
	  fftw-devel binutils-devel libusb-devel mesa-libGL-devel mesa-libGLES-devel
elif [ $(which zypper) ]; then # install rpm dependencies for OpenSUSE based systems
	zypper install make cmake fakeroot gcc-c++ libqt5-qtbase libqt5-qttools libqt5-qttranslations \
	  libusb-1_0 Mesa-libGL1 Mesa-libGLESv2 fftw3
else
	echo "No package management tool found, cannot install build requirements automatically"
	exit 1
fi

