#!/bin/sh

# execute this script as root to install the build dependencies

if [ $(id -u) != 0 ]; then
	echo "This script must be executed as root"
	exit 1
fi

# find the appropriate package management tool and install some packages
#
if [ $(which apt) ]; then # install deb dependencies for Debian (as well as Ubuntu) based systems
	apt install g++ make cmake fakeroot rpm \
	  libfftw3-dev binutils-dev libusb-1.0-0-dev libcups2-dev libxkbcommon-dev\
	  libqt6core6t64 libqt6gui6 libqt6widgets6 libqt6printsupport6 \
	  libqt6opengl6 libqt6openglwidgets6 qt6-tools-dev
elif [ $(which dnf) ]; then # install rpm dependencies for Fedora based systems
	# TODO: add dependencies if needed
	dnf install make cmake fakeroot gcc-c++ qt6-qtbase-gui qt6-qttools-devel qt6-qttranslations \
	  fftw-devel binutils-devel libusb-devel mesa-libGL-devel mesa-libGLES-devel
elif [ $(which zypper) ]; then # install rpm dependencies for OpenSUSE based systems
	# TODO: add dependencies if needed
	zypper install make cmake fakeroot gcc-c++ libqt6-qtbase libqt6-qttools libqt6-qttranslations \
	  libusb-1_0 Mesa-libGL1 Mesa-libGLESv2 fftw3
else
	echo "No package management tool found, cannot install build requirements automatically"
	exit 1
fi

